config/routes.rb
Rails.application.routes.draw do
  resources :accounts, only: [:create]
  resources :connections, only: [:new, :create]
  resources :devices, only: [:index, :create, :destroy]
  resources :messages, only: [:show, :create]

  get "manifest" => "home#manifest", constraints: { format: :json }

  if Rails.env.production?
    get "/service-worker" => "service_worker#index", constraints: { format: :js }
  end

  root to: "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :devices
  has_many :messages

  before_create :generate_pin, unless: :pin?

  private

  def generate_pin
    loop do
      new_pin = SecureRandom.base58(5)

      unless self.class.exists?(pin: new_pin)
        self.pin = new_pin
        break
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :account

  validates :endpoint, presence: true, uniqueness: true

  delegate :name, :version, :platform, :device, to: :parsed_user_agent, prefix: :ua

  def parsed_user_agent
    @parsed_user_agent ||= Browser.new(user_agent)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :account

  validates :title, :body, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def create
    account = Account.new

    if account.save
      cookies.permanent[:account_pin] = account.pin
      flash.notice = "Account created"
    else
      flash.alert = "Unable to create account"
    end

    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def assign_and_authenticate_account
    if cookies[:account_pin].blank?
      account_error("You need to be connected to an account", status: :forbidden) and return
    end

    @account = Account.find_by(pin: cookies[:account_pin])

    unless @account
      account_error("Account not found", status: :not_found) and return
    end
  end

  def account_error(message, status: :ok)
    respond_to do |format|
      format.html { redirect_to root_path, alert: message }
      format.json { render json: { errors: { base: message } }, status: status }
      format.js do
        flash.alert = message
        render js: %Q{window.location = "#{j root_path}"}
      end
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def new
    @account = Account.new
  end

  def create
    account = Account.find_by(pin: account_params[:pin])

    if account.present?
      cookies.permanent[:account_pin] = account.pin
      redirect_to root_path
    else
      @account = account_with_error
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:pin)
  end

  def account_with_error
    Account.new.tap do |account|
      account.errors.add(:pin, "not found")
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :assign_and_authenticate_account

  def index
    @devices = @account.devices.order(:created_at)
  end

  def create
    existing_device = @account.devices.find_by(endpoint: device_params[:endpoint])

    if existing_device
      render json: existing_device, status: :ok and return
    end

    device = @account.devices.build(device_params.merge user_agent: request.user_agent)

    if device.save
      render json: device, status: :created
    else
      render json: { errors: device.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    device = @account.devices.find_by! endpoint: Base64.decode64(params[:id])

    if device.destroy
      head :no_content
    else
      render json: { errors: device.errors }, status: :unprocessable_entity
    end
  end

  private

  def device_params
    params.require(:device).permit(:endpoint, :p256dh, :auth)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if cookies[:account_pin].present?
      @account = Account.find_by!(pin: cookies[:account_pin])
      @message = @account.messages.build
    end
  end

  def manifest
    manifest_hash = {
      name: "Browser notifications example",
      gcm_sender_id: ENV["GCM_SENDER_ID"]
    }

    render json: manifest_hash
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :assign_and_authenticate_account

  def show
    @message = @account.messages.find(params[:id])
  end

  def create
    @message = @account.messages.build(message_params)

    Notifier.new(@message).notify_all_devices if @message.save

    respond_to do |format|
      format.js { render :create }
    end
  end

  private

  def message_params
    params.require(:message).permit(:title, :body)
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ActionController::Metal
  include ActionController::DataStreaming

  def index
    filename = Rails.application.assets_manifest.assets["service-worker.js"]

    send_file Rails.root.join("public", "assets", filename).to_s, disposition: "inline"
  end

  private

  def send_file_headers!(options)
    super

    response.cache_control.replace({})
    headers["Cache-Control"] = "private, max-age=0, no-cache"

    headers.delete("Content-Disposition")
    headers.delete("Content-Transfer-Encoding")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = {
    "alert" => "warning",
    "notice" => "info"
  }
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end

  def flash_class(key)
    FLASH_CLASSES[key]
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| -%>
    <div class="alert alert-<%= flash_class key %> flash"><%= value %></div>
  <% end -%>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/connections/new.html.erb
<div class="container text-center">
  <h1>Connect to an account</h1>

  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= simple_form_for @account, url: connections_path do |f| %>
        <%= f.input :pin, label: "Account PIN", input_html: { class: "input-lg text-center", maxlength: 5 } %>

        <%= f.submit "Connect", class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/devices/index.html.erb
<h2 class="h3">Connected devices</h2>

<% if @account.devices.any? %>
  <ul>
    <% @account.devices.each do |device| %>
      <li>
        <%= device.ua_device.unknown? ? "Browser" : device.ua_device.name %>:
        <%= device.ua_name %> <%= device.ua_version %>
        on
        <%= device.ua_platform.name %> <%= device.ua_platform.version %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No devices connected yet</p>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <% if @account.present? %>
      <h4>Your pin is:</h4>
      <h1><%= @account.pin %></h1>

      <button type="button" class="btn btn-primary js-notifications-btn" disabled>
        Enable notifications on this device
      </button>
    <% else %>
      <h1>Browser notifications example</h1>
      <br>

      <%= link_to "Generate account", accounts_path, method: :post, class: "btn btn-primary btn-lg", data: { disable_with: "Generating..." } %>
      <%= link_to "Connect to account", new_connection_path, class: "btn btn-default btn-lg" %>
    <% end %>

    <div id="errors-container"></div>
  </div>
</div>

<% if @account.present? %>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <iframe src="<%= devices_path %>" id="devices-iframe" frameborder="0"></iframe>
      </div>

      <div class="col-sm-6">
        <h2 class="h3">Send a message</h2>

        <%= render "messages/form", message: @message %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <link rel="manifest" href="/manifest.json">
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for message, remote: true do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>

  <%= f.submit "Send message", class: "btn btn-primary", data: { disable_with: "Sending..." } %>
<% end %>

app/views/messages/create.js.erb
<% message = @message.persisted? ? @account.messages.build : @message %>

$("#new_message").replaceWith("<%= j render 'form', message: message %>");

<% if @message.persisted? %>
  $(".flash").remove();
  $("<div/>").addClass("alert alert-info flash").text("Message sent!").prependTo("body");
  $("html, body").animate({ scrollTop: 0 });
<% end %>

app/views/messages/show.html.erb
<div class="container">
  <div>
    <%= link_to "Back", root_path %>
  </div>

  <h1><%= @message.title %></h1>
  <h2 class="h4"><small><%= l @message.created_at %></small></h2>

  <blockquote>
    <%= simple_format @message.body %>
  </blockquote>
</div>